services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOFR_ENV: docker
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: ims
      POSTGRES_PASSWORD: ims
      POSTGRES_DB: inventory_management_system
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ims -d inventory_management_system" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080